// SVG export.
//
// Rebuilds the decision tree as inline SVG — fully editable in Figma /
// Illustrator / PowerPoint. Theme-aware via CSS variables resolved at
// export time (snapshots the active theme).

import { rootOf, childrenOf } from '../model/tree.js';
import { meanOfInput } from '../sim/distributions.js';

// Shape geometry — mirrors /canvas/nodes.js.
const DEC = { w: 76,  h: 76,  r: 12 };
const CHA = { r: 34 };
const TER = { w: 196, h: 60, r: 12 };

const fmt = (v, cur = '$') => {
  if (v === null || v === undefined || !Number.isFinite(v)) return '—';
  const a = Math.abs(v);
  const s = v < 0 ? '-' : '';
  if (a >= 1e9) return `${s}${cur}${(a / 1e9).toFixed(2)}B`;
  if (a >= 1e6) return `${s}${cur}${(a / 1e6).toFixed(2)}M`;
  if (a >= 1e3) return `${s}${cur}${(a / 1e3).toFixed(1)}K`;
  return `${s}${cur}${a.toFixed(0)}`;
};

export function buildTreeSvg(tree, opts = {}) {
  const cs = getComputedStyle(document.documentElement);
  const bg         = cs.getPropertyValue('--bg').trim();
  const text       = cs.getPropertyValue('--text').trim();
  const textMuted  = cs.getPropertyValue('--text-muted').trim();
  const panel      = cs.getPropertyValue('--panel').trim();
  const nodeFill   = cs.getPropertyValue('--node-fill').trim();
  const nodeStroke = cs.getPropertyValue('--node-stroke').trim();
  const accent     = cs.getPropertyValue('--accent').trim();
  const hero       = cs.getPropertyValue('--hero').trim();
  const line       = cs.getPropertyValue('--line').trim();

  const root = rootOf(tree);
  if (!root) return blankSvg();

  // Compute bounding box.
  let minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity;
  for (const n of tree.nodes) {
    const w = n.type === 'decision' ? DEC.w : n.type === 'chance' ? CHA.r * 2 : TER.w;
    const h = n.type === 'decision' ? DEC.h : n.type === 'chance' ? CHA.r * 2 : TER.h;
    minX = Math.min(minX, n.x - w / 2);
    minY = Math.min(minY, n.y - h / 2);
    maxX = Math.max(maxX, n.x + w / 2);
    maxY = Math.max(maxY, n.y + h / 2);
  }
  const pad = 40;
  const vbX = minX - pad, vbY = minY - pad;
  const vbW = (maxX - minX) + pad * 2;
  const vbH = (maxY - minY) + pad * 2;

  const bestSet = new Set(opts.bestPathIds || []);
  const terminalEmvs = opts.terminalEmvs || null;
  const currency = tree.meta?.currency || '$';

  // Build edges first (so nodes sit on top).
  const edges = [];
  for (const child of tree.nodes) {
    if (!child.parentId) continue;
    const parent = tree.nodes.find(n => n.id === child.parentId);
    if (!parent) continue;
    const isBest = bestSet.has(parent.id) && bestSet.has(child.id);
    edges.push(edgeMarkup(parent, child, isBest, hero, line, panel, textMuted, accent, tree));
  }

  const nodes = tree.nodes.map(n => nodeMarkup(n, {
    selected: false,
    best: bestSet.has(n.id),
    nodeFill, nodeStroke, text, textMuted, accent, hero,
    emv: terminalEmvs ? terminalEmvs[n.id] : undefined,
    currency
  })).join('\n');

  return `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg"
     viewBox="${vbX} ${vbY} ${vbW} ${vbH}"
     width="${Math.round(vbW)}" height="${Math.round(vbH)}"
     font-family="Inter, system-ui, sans-serif"
     style="background:${bg}">
  <title>${escAttr(tree.meta?.title || 'Decision Tree')}</title>
  <desc>Generated by Arbor — Decision Intelligence.</desc>
  <rect x="${vbX}" y="${vbY}" width="${vbW}" height="${vbH}" fill="${bg}"/>
  <g class="edges">${edges.join('\n')}</g>
  <g class="nodes">${nodes}</g>
</svg>`;
}

function edgeMarkup(parent, child, isBest, hero, line, panel, textMuted, accent, tree) {
  const from = nodePort(parent, 'right');
  const to   = nodePort(child,  'left');
  const midX = (from.x + to.x) / 2;
  const stroke = isBest ? hero : line;
  const width  = isBest ? 2.4 : 1.2;
  const labelParts = [];
  if (child.branchLabel) labelParts.push(child.branchLabel);
  if (parent.type === 'chance' && child.branchProb) {
    const mu = meanOfInput(child.branchProb);
    const isDist = child.branchProb.mode === 'distribution';
    labelParts.push((isDist ? '~' : '') + (mu * 100).toFixed(isDist ? 1 : 0) + '%');
  }
  let labelSvg = '';
  if (labelParts.length) {
    const text = labelParts.join('  ·  ');
    const labelY = (from.y + to.y) / 2 - 10;
    const w = Math.max(56, text.length * 5.5);
    labelSvg = `
      <g>
        <rect x="${midX - w/2}" y="${labelY - 9}" width="${w}" height="18" rx="4"
              fill="${panel}" stroke="${line}" stroke-width="0.5"/>
        <text x="${midX}" y="${labelY + 3}" text-anchor="middle"
              font-family="DM Mono, ui-monospace, monospace" font-size="10"
              fill="${isBest ? hero : textMuted}">${escText(text)}</text>
      </g>`;
  }
  return `
    <path d="M ${from.x} ${from.y} C ${midX} ${from.y}, ${midX} ${to.y}, ${to.x} ${to.y}"
          fill="none" stroke="${stroke}" stroke-width="${width}"/>
    ${labelSvg}`;
}

function nodePort(node, side) {
  const w = node.type === 'decision' ? DEC.w : node.type === 'chance' ? CHA.r * 2 : TER.w;
  if (side === 'right') return { x: node.x + w / 2, y: node.y };
  return { x: node.x - w / 2, y: node.y };
}

function nodeMarkup(n, ctx) {
  const stroke = ctx.best ? ctx.hero : ctx.nodeStroke;
  const sw = ctx.best ? 1.6 : 1.0;
  if (n.type === 'decision') {
    return `
      <g>
        <rect x="${n.x - DEC.w/2}" y="${n.y - DEC.h/2}" width="${DEC.w}" height="${DEC.h}"
              rx="${DEC.r}" fill="${ctx.nodeFill}" stroke="${stroke}" stroke-width="${sw}"/>
        <text x="${n.x}" y="${n.y - 4}" text-anchor="middle"
              font-family="Syne, system-ui, sans-serif" font-size="14" font-weight="600"
              fill="${ctx.accent}">◆</text>
        <text x="${n.x}" y="${n.y + 22}" text-anchor="middle"
              font-size="12" font-weight="600" fill="${ctx.text}">${escText(trunc(n.label, 16))}</text>
      </g>`;
  }
  if (n.type === 'chance') {
    return `
      <g>
        <circle cx="${n.x}" cy="${n.y}" r="${CHA.r}"
                fill="${ctx.nodeFill}" stroke="${stroke}" stroke-width="${sw}"/>
        <text x="${n.x}" y="${n.y}" text-anchor="middle" dominant-baseline="middle"
              font-family="Syne, system-ui, sans-serif" font-size="16" font-weight="500"
              fill="${ctx.accent}">◎</text>
        <text x="${n.x}" y="${n.y + 18}" text-anchor="middle"
              font-size="11" font-weight="500" fill="${ctx.textMuted}">${escText(trunc(n.label, 14))}</text>
      </g>`;
  }
  // Terminal
  const hasEmv = typeof ctx.emv === 'number';
  const mu = n.payoff ? meanOfInput(n.payoff) : 0;
  const muTxt = (n.payoff?.mode === 'distribution' ? '' : '') + fmt(mu, ctx.currency)
              + (n.payoff?.mode === 'distribution' ? ' · μ' : '');
  return `
    <g>
      <rect x="${n.x - TER.w/2}" y="${n.y - TER.h/2}" width="${TER.w}" height="${TER.h}"
            rx="${TER.r}" fill="${ctx.nodeFill}" stroke="${stroke}" stroke-width="${sw}"/>
      <text x="${n.x}" y="${hasEmv ? n.y - 12 : n.y - 4}" text-anchor="middle"
            font-size="12" font-weight="600" fill="${ctx.text}">${escText(trunc(n.label, 22))}</text>
      <text x="${n.x}" y="${hasEmv ? n.y + 4 : n.y + 14}" text-anchor="middle"
            font-family="DM Mono, ui-monospace, monospace" font-size="11"
            fill="${mu >= 0 ? ctx.accent : ctx.hero}">${escText(muTxt)}</text>
      ${hasEmv ? `
        <text x="${n.x}" y="${n.y + 20}" text-anchor="middle"
              font-family="DM Mono, ui-monospace, monospace" font-size="10"
              fill="${ctx.hero}">EMV ${escText(fmt(ctx.emv, ctx.currency))}</text>` : ''}
    </g>`;
}

function trunc(s, n) {
  s = s || '';
  return s.length > n ? s.slice(0, n - 1) + '…' : s;
}
function escText(s) { return String(s ?? '').replace(/[<>&]/g, c => ({'<':'&lt;','>':'&gt;','&':'&amp;'}[c])); }
function escAttr(s) { return String(s ?? '').replace(/[<>&"]/g, c => ({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;'}[c])); }
function blankSvg() {
  return `<?xml version="1.0" encoding="UTF-8"?><svg xmlns="http://www.w3.org/2000/svg" width="200" height="100"><text x="10" y="50">Empty tree</text></svg>`;
}

// Trigger a browser download of the SVG.
export function exportSvg(tree, opts = {}) {
  const svg = buildTreeSvg(tree, opts);
  const filename = slugFile(tree, 'svg');
  const blob = new Blob([svg], { type: 'image/svg+xml;charset=utf-8' });
  triggerDownload(blob, filename);
}

export function slugFile(tree, ext) {
  const title = (tree.meta?.title || 'decision').toLowerCase()
    .replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
  const d = new Date();
  const ymd = `${d.getFullYear()}${String(d.getMonth() + 1).padStart(2, '0')}${String(d.getDate()).padStart(2, '0')}`;
  return `arbor-decision-${title}-${ymd}.${ext}`;
}

export function triggerDownload(blob, filename) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 0);
}
